install! 'cocoapods', :deterministic_uuids => false
platform :ios, '12.0'
swift_version = "5"

use_frameworks!
enable_bitcode_for_prebuilt_frameworks!
inhibit_all_warnings!


target 'KodaBotsSample' do
  
 pod 'KodaBotsSDK', :path => '../KodaBotsSDK'

end
